blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/kentstone84/PyTorch-2.10.0a0-for-Linux-/blob/main/README.md
    about: Read the documentation for guides and information
  - name: Discussions
    url: https://github.com/kentstone84/PyTorch-2.10.0a0-for-Linux-/discussions
    about: Ask questions and discuss with the community
